apiVersion: v1
kind: ConfigMap
metadata:
  name: pool-config
data:
  pool-config.lua: |
    return {
      allowed_paths = {
        ["amazon"] = "@webapp1",
        ["audible"] = "@webapp2"
      },
      default_pool = "@reject"
    }